### ISSUE TITLE
Upgrading to mapnik ~3.4.14

### ISSUE THREAD

**Issue by mapsam** [mapbox/raster-tile-query#12]
Working through https://github.com/mapbox/mapnik-swoop/issues/4 and want to upgrade this module's `mapnik` version to stay in sync with all other `node-mapnik` binaries.

Here's my error:

```
~/mapbox/raster-tile-query[mapnik-upgrade]$ npm test

> raster-tile-query@0.0.1 test /Users/mapsam/mapbox/raster-tile-query
> mocha


  ․․․․․․․․․․․․․․․․․․

  13 passing (54ms)
  5 failing

  1) Getting pixels should return the correct pixel value from a valid query:

      Uncaught AssertionError: "[{\"pixel\":4285286517,\"latlng\":{\"lat\":39.24282321740235,\"lng\":-121.53676986694335},\"id\":0}]" == "[{\"pixel\":{\"a\":255,\"b\":108,\"g\":72,\"r\":117},\"latlng\":{\"lat\":39.24282321740235,\"lng\":-121.53676986694335},\"id\":
      + expected - actual

      +[{"pixel":{"a":255,"b":108,"g":72,"r":117},"latlng":{"lat":39.24282321740235,"lng":-121.53676986694335},"id":0}]
      -[{"pixel":4285286517,"latlng":{"lat":39.24282321740235,"lng":-121.53676986694335},"id":0}]
      
      at /Users/mapsam/mapbox/raster-tile-query/test/test.js:125:24
      at Object.getPixels (/Users/mapsam/mapbox/raster-tile-query/index.js:37:12)
      at /Users/mapsam/mapbox/raster-tile-query/test/test.js:124:17
      at /Users/mapsam/mapbox/raster-tile-query/test/test.js:12:16
      at fs.js:272:14
      at /Users/mapsam/mapbox/raster-tile-query/node_modules/mocha/node_modules/glob/node_modules/graceful-fs/graceful-fs.js:104:5
      at Object.oncomplete (fs.js:108:15)

  2) Return the correct results from a query should work for multiple tile queries:

      Uncaught AssertionError: "[{\"pixel\":4285286517,\"latlng\":{\"lat\":39.24282321740235,\"lng\":-121.53676986694335},\"id\":0},{\"pixel\":4285809058,\"lat == "[{\"pixel\":{\"a\":255,\"b\":108,\"g\":72,\"r\":117},\"latlng\":{\"lat\":39.24282321740235,\"lng\":-121.53676986694335},\"id\":
      + expected - actual

      +[{"pixel":{"a":255,"b":108,"g":72,"r":117},"latlng":{"lat":39.24282321740235,"lng":-121.53676986694335},"id":0},{"pixel":{"a":255,"b":116,"g":65,"r":162},"latlng":{"lat":39.241626684998266,"lng":-121.53685569763182},"id":1},{"pixel":{"a":255,"b":119,"g":69,"r":170},"latlng":{"lat":39.241626684998266,"lng":-121.53565406799318},"id":2},{"pixel":{"a":255,"b":118,"g":66,"r":171},"latlng":{"lat":39.24056308350469,"lng":-121.53642654418945},"id":3},{"pixel":{"a":255,"b":115,"g":72,"r":145},"latlng":{"lat":39.239499465884755,"lng":-121.53582572937012},"id":4},{"pixel":{"a":255,"b":98,"g":67,"r":104},"latlng":{"lat":39.23873498075964,"lng":-121.53672695159912},"id":5},{"pixel":{"a":255,"b":107,"g":66,"r":133},"latlng":{"lat":39.23743866085578,"lng":-121.53651237487793},"id":6},{"pixel":{"a":255,"b":115,"g":72,"r":152},"latlng":{"lat":39.236707392907185,"lng":-121.53779983520508},"id":7},{"pixel":{"a":255,"b":101,"g":58,"r":125},"latlng":{"lat":39.23584315732298,"lng":-121.53668403625488},"id":8},{"pixel":{"a":255,"b":107,"g":59,"r":161},"latlng":{"lat":39.23484594918998,"lng":-121.53762817382814},"id":9},{"pixel":{"a":255,"b":108,"g":64,"r":163},"latlng":{"lat":39.23398,"lng":-121.53637},"id":10}]
      -[{"pixel":4285286517,"latlng":{"lat":39.24282321740235,"lng":-121.53676986694335},"id":0},{"pixel":4285809058,"latlng":{"lat":39.241626684998266,"lng":-121.53685569763182},"id":1},{"pixel":4286006698,"latlng":{"lat":39.241626684998266,"lng":-121.53565406799318},"id":2},{"pixel":4285940395,"latlng":{"lat":39.24056308350469,"lng":-121.53642654418945},"id":3},{"pixel":4285745297,"latlng":{"lat":39.239499465884755,"lng":-121.53582572937012},"id":4},{"pixel":4284629864,"latlng":{"lat":39.23873498075964,"lng":-121.53672695159912},"id":5},{"pixel":4285219461,"latlng":{"lat":39.23743866085578,"lng":-121.53651237487793},"id":6},{"pixel":4285745304,"latlng":{"lat":39.236707392907185,"lng":-121.53779983520508},"id":7},{"pixel":4284824189,"latlng":{"lat":39.23584315732298,"lng":-121.53668403625488},"id":8},{"pixel":4285217697,"latlng":{"lat":39.23484594918998,"lng":-121.53762817382814},"id":9},{"pixel":4285284515,"latlng":{"lat":39.23398,"lng":-121.53637},"id":10}]
      
      at /Users/mapsam/mapbox/raster-tile-query/test/test.js:177:24
      at queriesDone (/Users/mapsam/mapbox/raster-tile-query/index.js:207:16)
      at notify (/Users/mapsam/mapbox/raster-tile-query/node_modules/queue-async/queue.js:46:21)
      at Object.q.awaitAll (/Users/mapsam/mapbox/raster-tile-query/node_modules/queue-async/queue.js:68:25)
      at Object.multiQuery (/Users/mapsam/mapbox/raster-tile-query/index.js:220:16)
      at /Users/mapsam/mapbox/raster-tile-query/test/test.js:176:17
      at notify (/Users/mapsam/mapbox/raster-tile-query/node_modules/queue-async/queue.js:46:21)
      at /Users/mapsam/mapbox/raster-tile-query/node_modules/queue-async/queue.js:39:16
      at /Users/mapsam/mapbox/raster-tile-query/index.js:187:20
      at /Users/mapsam/mapbox/raster-tile-query/test/test.js:12:16
      at fs.js:272:14
      at /Users/mapsam/mapbox/raster-tile-query/node_modules/mocha/node_modules/glob/node_modules/graceful-fs/graceful-fs.js:104:5
      at Object.oncomplete (fs.js:108:15)

  3) Return the correct results from a query should work for multiple tile queries and select the correct zoom:

      Uncaught AssertionError: "[{\"pixel\":4284957065,\"latlng\":{\"lat\":39.24282321740235,\"lng\":-121.53676986694335},\"id\":0},{\"pixel\":4285483414,\"lat == "[{\"pixel\":{\"a\":255,\"b\":103,\"g\":65,\"r\":137},\"latlng\":{\"lat\":39.24282321740235,\"lng\":-121.53676986694335},\"id\":
      + expected - actual

      +[{"pixel":{"a":255,"b":103,"g":65,"r":137},"latlng":{"lat":39.24282321740235,"lng":-121.53676986694335},"id":0},{"pixel":{"a":255,"b":111,"g":73,"r":150},"latlng":{"lat":39.241626684998266,"lng":-121.53685569763182},"id":1},{"pixel":{"a":255,"b":117,"g":70,"r":164},"latlng":{"lat":39.241626684998266,"lng":-121.53565406799318},"id":2},{"pixel":{"a":255,"b":112,"g":67,"r":154},"latlng":{"lat":39.24056308350469,"lng":-121.53642654418945},"id":3},{"pixel":{"a":255,"b":112,"g":73,"r":147},"latlng":{"lat":39.239499465884755,"lng":-121.53582572937012},"id":4},{"pixel":{"a":255,"b":102,"g":63,"r":137},"latlng":{"lat":39.23873498075964,"lng":-121.53672695159912},"id":5},{"pixel":{"a":255,"b":114,"g":78,"r":138},"latlng":{"lat":39.23743866085578,"lng":-121.53651237487793},"id":6},{"pixel":{"a":255,"b":118,"g":72,"r":155},"latlng":{"lat":39.236707392907185,"lng":-121.53779983520508},"id":7},{"pixel":{"a":255,"b":106,"g":60,"r":141},"latlng":{"lat":39.23584315732298,"lng":-121.53668403625488},"id":8},{"pixel":{"a":255,"b":107,"g":66,"r":143},"latlng":{"lat":39.23484594918998,"lng":-121.53762817382814},"id":9},{"pixel":{"a":255,"b":121,"g":95,"r":148},"latlng":{"lat":39.23398,"lng":-121.53637},"id":10}]
      -[{"pixel":4284957065,"latlng":{"lat":39.24282321740235,"lng":-121.53676986694335},"id":0},{"pixel":4285483414,"latlng":{"lat":39.241626684998266,"lng":-121.53685569763182},"id":1},{"pixel":4285875876,"latlng":{"lat":39.241626684998266,"lng":-121.53565406799318},"id":2},{"pixel":4285547418,"latlng":{"lat":39.24056308350469,"lng":-121.53642654418945},"id":3},{"pixel":4285548947,"latlng":{"lat":39.239499465884755,"lng":-121.53582572937012},"id":4},{"pixel":4284891017,"latlng":{"lat":39.23873498075964,"lng":-121.53672695159912},"id":5},{"pixel":4285681290,"latlng":{"lat":39.23743866085578,"lng":-121.53651237487793},"id":6},{"pixel":4285941915,"latlng":{"lat":39.236707392907185,"lng":-121.53779983520508},"id":7},{"pixel":4285152397,"latlng":{"lat":39.23584315732298,"lng":-121.53668403625488},"id":8},{"pixel":4285219471,"latlng":{"lat":39.23484594918998,"lng":-121.53762817382814},"id":9},{"pixel":4286144404,"latlng":{"lat":39.23398,"lng":-121.53637},"id":10}]
      
      at /Users/mapsam/mapbox/raster-tile-query/test/test.js:193:24
      at queriesDone (/Users/mapsam/mapbox/raster-tile-query/index.js:207:16)
      at notify (/Users/mapsam/mapbox/raster-tile-query/node_modules/queue-async/queue.js:46:21)
      at Object.q.awaitAll (/Users/mapsam/mapbox/raster-tile-query/node_modules/queue-async/queue.js:68:25)
      at Object.multiQuery (/Users/mapsam/mapbox/raster-tile-query/index.js:220:16)
      at /Users/mapsam/mapbox/raster-tile-query/test/test.js:192:17
      at notify (/Users/mapsam/mapbox/raster-tile-query/node_modules/queue-async/queue.js:46:21)
      at /Users/mapsam/mapbox/raster-tile-query/node_modules/queue-async/queue.js:39:16
      at /Users/mapsam/mapbox/raster-tile-query/index.js:187:20
      at /Users/mapsam/mapbox/raster-tile-query/test/test.js:12:16
      at fs.js:272:14
      at /Users/mapsam/mapbox/raster-tile-query/node_modules/mocha/node_modules/glob/node_modules/graceful-fs/graceful-fs.js:104:5
      at Object.oncomplete (fs.js:108:15)

  4) Return the correct results from a query should work for single-point queries:

      Uncaught AssertionError: "[{\"pixel\":4285286517,\"latlng\":{\"lat\":39.24282321740235,\"lng\":-121.53676986694335},\"id\":0}]" == "[{\"pixel\":{\"a\":255,\"b\":108,\"g\":72,\"r\":117},\"latlng\":{\"lat\":39.24282321740235,\"lng\":-121.53676986694335},\"id\":
      + expected - actual

      +[{"pixel":{"a":255,"b":108,"g":72,"r":117},"latlng":{"lat":39.24282321740235,"lng":-121.53676986694335},"id":0}]
      -[{"pixel":4285286517,"latlng":{"lat":39.24282321740235,"lng":-121.53676986694335},"id":0}]
      
      at /Users/mapsam/mapbox/raster-tile-query/test/test.js:212:24
      at queriesDone (/Users/mapsam/mapbox/raster-tile-query/index.js:207:16)
      at notify (/Users/mapsam/mapbox/raster-tile-query/node_modules/queue-async/queue.js:46:21)
      at Object.q.awaitAll (/Users/mapsam/mapbox/raster-tile-query/node_modules/queue-async/queue.js:68:25)
      at Object.multiQuery (/Users/mapsam/mapbox/raster-tile-query/index.js:220:16)
      at /Users/mapsam/mapbox/raster-tile-query/test/test.js:211:17
      at notify (/Users/mapsam/mapbox/raster-tile-query/node_modules/queue-async/queue.js:46:21)
      at /Users/mapsam/mapbox/raster-tile-query/node_modules/queue-async/queue.js:39:16
      at /Users/mapsam/mapbox/raster-tile-query/index.js:187:20
      at /Users/mapsam/mapbox/raster-tile-query/test/test.js:12:16
      at fs.js:272:14
      at /Users/mapsam/mapbox/raster-tile-query/node_modules/mocha/node_modules/glob/node_modules/graceful-fs/graceful-fs.js:104:5
      at Object.oncomplete (fs.js:108:15)

  5) Return the correct results from a query should return null for points in a non-existent tile, but not fail if at least one tile has valid points:

      Uncaught AssertionError: "[{\"pixel\":null,\"latlng\":{\"lat\":33.24282321740235,\"lng\":-120.53676986694335},\"id\":0},{\"pixel\":null,\"latlng\":{\"lat == "[{\"pixel\":null,\"latlng\":{\"lat\":33.24282321740235,\"lng\":-120.53676986694335},\"id\":0},{\"pixel\":null,\"latlng\":{\"lat
      + expected - actual

      +[{"pixel":null,"latlng":{"lat":33.24282321740235,"lng":-120.53676986694335},"id":0},{"pixel":null,"latlng":{"lat":33.241626684998266,"lng":-120.53685569763182},"id":1},{"pixel":null,"latlng":{"lat":33.241626684998266,"lng":-121.53565406799318},"id":2},{"pixel":{"a":255,"b":118,"g":66,"r":171},"latlng":{"lat":39.24056308350469,"lng":-121.53642654418945},"id":3},{"pixel":{"a":255,"b":115,"g":72,"r":145},"latlng":{"lat":39.239499465884755,"lng":-121.53582572937012},"id":4},{"pixel":{"a":255,"b":98,"g":67,"r":104},"latlng":{"lat":39.23873498075964,"lng":-121.53672695159912},"id":5},{"pixel":{"a":255,"b":107,"g":66,"r":133},"latlng":{"lat":39.23743866085578,"lng":-121.53651237487793},"id":6},{"pixel":{"a":255,"b":115,"g":72,"r":152},"latlng":{"lat":39.236707392907185,"lng":-121.53779983520508},"id":7},{"pixel":{"a":255,"b":101,"g":58,"r":125},"latlng":{"lat":39.23584315732298,"lng":-121.53668403625488},"id":8},{"pixel":null,"latlng":{"lat":40.23484594918998,"lng":-111.53762817382814},"id":9},{"pixel":null,"latlng":{"lat":40.23398,"lng":-111.53637},"id":10}]
      -[{"pixel":null,"latlng":{"lat":33.24282321740235,"lng":-120.53676986694335},"id":0},{"pixel":null,"latlng":{"lat":33.241626684998266,"lng":-120.53685569763182},"id":1},{"pixel":null,"latlng":{"lat":33.241626684998266,"lng":-121.53565406799318},"id":2},{"pixel":4285940395,"latlng":{"lat":39.24056308350469,"lng":-121.53642654418945},"id":3},{"pixel":4285745297,"latlng":{"lat":39.239499465884755,"lng":-121.53582572937012},"id":4},{"pixel":4284629864,"latlng":{"lat":39.23873498075964,"lng":-121.53672695159912},"id":5},{"pixel":4285219461,"latlng":{"lat":39.23743866085578,"lng":-121.53651237487793},"id":6},{"pixel":4285745304,"latlng":{"lat":39.236707392907185,"lng":-121.53779983520508},"id":7},{"pixel":4284824189,"latlng":{"lat":39.23584315732298,"lng":-121.53668403625488},"id":8},{"pixel":null,"latlng":{"lat":40.23484594918998,"lng":-111.53762817382814},"id":9},{"pixel":null,"latlng":{"lat":40.23398,"lng":-111.53637},"id":10}]
      
      at /Users/mapsam/mapbox/raster-tile-query/test/test.js:229:24
      at queriesDone (/Users/mapsam/mapbox/raster-tile-query/index.js:207:16)
      at notify (/Users/mapsam/mapbox/raster-tile-query/node_modules/queue-async/queue.js:46:21)
      at Object.q.awaitAll (/Users/mapsam/mapbox/raster-tile-query/node_modules/queue-async/queue.js:68:25)
      at Object.multiQuery (/Users/mapsam/mapbox/raster-tile-query/index.js:220:16)
      at /Users/mapsam/mapbox/raster-tile-query/test/test.js:228:17
      at notify (/Users/mapsam/mapbox/raster-tile-query/node_modules/queue-async/queue.js:46:21)
      at /Users/mapsam/mapbox/raster-tile-query/node_modules/queue-async/queue.js:39:16
      at /Users/mapsam/mapbox/raster-tile-query/index.js:187:20
      at /Users/mapsam/mapbox/raster-tile-query/test/test.js:12:16
      at fs.js:272:14
      at /Users/mapsam/mapbox/raster-tile-query/node_modules/mocha/node_modules/glob/node_modules/graceful-fs/graceful-fs.js:104:5
      at Object.oncomplete (fs.js:108:15)



npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

Will take a look through the mapnik changelog between `3.0` and `3.4` to see which functions are failing and how they've changed.

**Comment by mapsam** [comment]
Looks like pixel response from mapnik has changed, according to the test output. It expects something like this:

```js
// object with "a", "b", "g", and "r" params
"pixel":{"a":255,"b":108,"g":72,"r":117}
```

But returns something like this:

```js
// integer
{"pixel":4285286517}
```

Looks like color values were turned into an optional response in mapnik [3.2.0](https://github.com/mapnik/node-mapnik/blob/master/CHANGELOG.md#320). Changelog states: "Added the ability to return colors optionally with `getPixel` on `Image` objects". This means we need to pass `{get_color:true}` when using `getPixel()` in order to return `abgr` parameters ([thanks to node-mapnik tests showing this option](https://github.com/mapnik/node-mapnik/blob/master/test/image.test.js#L294)).

**Comment by mapsam** [comment]
Resolved in https://github.com/mapbox/raster-tile-query/pull/13
